version: '3.3'

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7.2.4-alpine
    expose:
      - 6379

  backend:
    restart: always
    build: ./backend/
    entrypoint: /app/backend_entrypoint.sh
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
      - ./backend/:/app/
    depends_on:
      - db

  worker:
    restart: always
    build: ./backend/
    command: celery -A alpha_project beat --loglevel=info
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
      - ./backend/:/app/
    depends_on:
      - backend
      - redis

  nginx:
    build: ./nginx/
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - static:/static/
      - media:/media/
    depends_on:
      - db
      - backend

volumes:
  postgres_data:
  static:
  media: