version: '2.0'

services:
  web:
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:16.1-alpine3.19
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env

  redis:
    image: redis:7.2.4-alpine
    expose:
      - 6379

  worker:
    build: ./src
    command: celery -A app.celery.celery_app worker -B --loglevel=info
    volumes:
      - ./src/:/usr/src/app/
    env_file: .env
    depends_on:
      - web
      - redis
  
  dashboard:
    build: ./src
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5556:5555
    env_file: .env
    depends_on:
      - web
      - redis
      - worker

volumes:
  postgres_data: