version: '3.3'

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    image: aleksey2299/alfa_backend:latest
    entrypoint: /app/backend_entrypoint.sh
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db

  nginx:
    image: aleksey2299/alfa_nginx:latest
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - static:/static/
      - media:/media/
    depends_on:
      - db
      - backend

  redis:
    image: redis:7.2.4-alpine
    expose:
      - 6379

  worker:
    restart: always
    image: aleksey2299/alfa_backend:latest
    command: celery -A alpha_project worker -B -l info
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - backend
      - redis

volumes:
  postgres_data:
  static:
  media: