# Generated by Django 4.2.9 on 2024-01-23 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_employee', to='users.employee', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='comment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_task', to='tasks.task', verbose_name='Задача'),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('name', 'idp')},
        ),
    ]
