# Generated by Django 4.2.9 on 2024-01-26 18:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date_end",
            field=models.DateField(
                verbose_name="Дата окончания выполнения задачи"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="date_start",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="Дата начала выполнения задачи",
            ),
        ),
    ]
