# Generated by Django 4.2.9 on 2024-02-08 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='название')),
                ('status_idp', models.CharField(choices=[('in_work', 'в работе'), ('cancelled', 'отменен'), ('not_completed', 'не выполнен'), ('done', 'выполнен')], default='in_work', max_length=20, verbose_name='статус')),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата начала')),
            ],
            options={
                'verbose_name': 'индивидуальный план развития',
                'ordering': ['date_start', 'id'],
            },
        ),
    ]
