# Generated by Django 4.2.9 on 2024-02-02 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Idp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название')),
                ('status_idp', models.CharField(choices=[('in_work', 'в работе'), ('canceled', 'отменен'), ('not_completed', 'не выполнен'), ('done', 'выполнен')], default='in_work', max_length=100, verbose_name='статус')),
                ('date_start', models.DateTimeField(auto_now_add=True, verbose_name='дата начала')),
                ('date_end', models.DateField(verbose_name='дата окончания')),
                ('director', mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='idp_director', to=settings.AUTH_USER_MODEL, verbose_name='директор')),
                ('employee', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idp_employee', to=settings.AUTH_USER_MODEL, verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'индивидуальный план развития',
                'ordering': ['date_start', 'id'],
                'unique_together': {('title', 'employee', 'date_start')},
            },
        ),
    ]
