# Generated by Django 4.2.9 on 2024-01-26 17:44

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("idps", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="idp",
            name="director",
            field=mptt.fields.TreeForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="idp_director",
                to=settings.AUTH_USER_MODEL,
                verbose_name="директор",
            ),
        ),
        migrations.AddField(
            model_name="idp",
            name="employee",
            field=mptt.fields.TreeForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="idp_employee",
                to=settings.AUTH_USER_MODEL,
                verbose_name="сотрудник",
            ),
        ),
        migrations.AddConstraint(
            model_name="idp",
            constraint=models.CheckConstraint(
                check=models.Q(("date_end__gt", models.F("date_start"))),
                name="check_start_date",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="idp",
            unique_together={("title", "employee", "date_start")},
        ),
    ]
