# Generated by Django 4.2.9 on 2024-01-21 21:07

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("idps", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="director_id",
            new_name="parent",
        ),
        migrations.AlterField(
            model_name="idp",
            name="director",
            field=mptt.fields.TreeOneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="idp_director",
                to="idps.employee",
                verbose_name="директор",
            ),
        ),
        migrations.AlterField(
            model_name="idp",
            name="employee",
            field=mptt.fields.TreeOneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="idp_employee",
                to="idps.employee",
                verbose_name="сотрудник",
            ),
        ),
    ]
