# Generated by Django 4.2.9 on 2024-01-20 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="director_id",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="idps.employee",
            ),
            preserve_default=False,
        ),
    ]
