# Generated by Django 4.2.9 on 2024-01-20 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idps", "0002_employee_director_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="director_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="idps.employee",
            ),
        ),
    ]
