# Generated by Django 4.2.9 on 2024-01-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idps", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idp",
            name="date_start",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="дата начала"
            ),
        ),
    ]
