# Generated by Django 4.2.9 on 2024-01-21 21:11

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("idps", "0002_rename_director_id_employee_parent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idp",
            name="director",
            field=mptt.fields.TreeForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="idp_director",
                to="idps.employee",
                verbose_name="директор",
            ),
        ),
        migrations.AlterField(
            model_name="idp",
            name="employee",
            field=mptt.fields.TreeForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="idp_employee",
                to="idps.employee",
                verbose_name="сотрудник",
            ),
        ),
    ]
