# Generated by Django 4.2.9 on 2024-01-27 18:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idps", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idp",
            name="date_start",
            field=models.DateField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="дата начала",
            ),
        ),
    ]
