# Generated by Django 4.2.9 on 2024-01-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("idps", "0003_alter_employee_director_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="idp",
            options={
                "ordering": ["id"],
                "verbose_name": "индивидуальный план развития",
            },
        ),
        migrations.AddConstraint(
            model_name="idp",
            constraint=models.CheckConstraint(
                check=models.Q(("date_end__gt", models.F("date_start"))),
                name="check_start_date",
            ),
        ),
    ]
