# Generated by Django 4.2.9 on 2024-01-21 23:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("idps", "0003_alter_idp_director_alter_idp_employee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="idp",
            options={
                "ordering": ["date_start", "id"],
                "verbose_name": "индивидуальный план развития",
            },
        ),
    ]
