# Generated by Django 4.2.9 on 2024-01-22 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("idps", "0004_alter_idp_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="parent",
            new_name="director",
        ),
    ]
