# Generated by Django 4.2.9 on 2024-02-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idps', '0004_alter_idp_status_idp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idp',
            name='status_idp',
            field=models.CharField(choices=[('in_work', 'в работе'), ('cancelled', 'отменен'), ('not_completed', 'не выполнен'), ('done', 'выполнен')], default='in_work', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='idp',
            name='title',
            field=models.CharField(max_length=256, verbose_name='название'),
        ),
    ]
