# Generated by Django 4.2.9 on 2024-01-22 17:41

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("idps", "0005_rename_parent_employee_director"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idp",
            name="director",
            field=mptt.fields.TreeForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="idp_director",
                to="idps.employee",
                verbose_name="директор",
            ),
        ),
    ]
