"""Some fix

Revision ID: edb9f5f397c2
Revises: b2a9377b36eb
Create Date: 2024-01-29 00:21:01.214287

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "edb9f5f397c2"
down_revision: Union[str, None] = "b2a9377b36eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "statusidp",
        ["in_work", "not_completed", "done", "canceled"],
        [TableReference("idp", "status_idp")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "statusidp",
        ["IN_WORK", "NOT_COMPLETED", "DONE", "CANCELED"],
        [TableReference("idp", "status_idp")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
