"""Fix Idp deleting

Revision ID: c31f7c66f358
Revises: d835d4b41c39
Create Date: 2024-02-01 01:38:09.049323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c31f7c66f358'
down_revision: Union[str, None] = 'd835d4b41c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('idp_director_id_fkey', 'idp', type_='foreignkey')
    op.create_foreign_key(None, 'idp', 'employee', ['director_id'], ['id'])
    op.drop_constraint('task_idp_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'idp', ['idp_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_idp_id_fkey', 'task', 'idp', ['idp_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'idp', type_='foreignkey')
    op.create_foreign_key('idp_director_id_fkey', 'idp', 'employee', ['director_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
