"""Removed idp date_end

Revision ID: b630821ccd78
Revises: 9d25b25e6777
Create Date: 2024-02-11 22:25:19.814246

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b630821ccd78"
down_revision: Union[str, None] = "9d25b25e6777"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("idp", "date_end")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "idp", sa.Column("date_end", sa.DATE(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
