"""Nullable settings for fields

Revision ID: 55708a1ef3f1
Revises: b630821ccd78
Create Date: 2024-02-14 00:11:21.778535

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "55708a1ef3f1"
down_revision: Union[str, None] = "b630821ccd78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "comment", "body_comment", existing_type=sa.VARCHAR(length=200), nullable=False
    )
    op.alter_column("comment", "task_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column(
        "control", "title", existing_type=sa.VARCHAR(length=100), nullable=False
    )
    op.alter_column("idp", "title", existing_type=sa.VARCHAR(length=100), nullable=False)
    op.alter_column("idp", "employee_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint("idp_director_id_fkey", "idp", type_="foreignkey")
    op.create_foreign_key(
        None, "idp", "employee", ["director_id"], ["id"], ondelete="SET NULL"
    )
    op.alter_column("task", "name", existing_type=sa.VARCHAR(length=100), nullable=False)
    op.alter_column("task", "description", existing_type=sa.TEXT(), nullable=False)
    op.alter_column("task", "idp_id", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("task", "date_start", existing_type=sa.DATE(), nullable=False)
    op.alter_column("task", "date_end", existing_type=sa.DATE(), nullable=False)
    op.alter_column("type", "name", existing_type=sa.VARCHAR(length=50), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("type", "name", existing_type=sa.VARCHAR(length=50), nullable=True)
    op.alter_column("task", "date_end", existing_type=sa.DATE(), nullable=True)
    op.alter_column("task", "date_start", existing_type=sa.DATE(), nullable=True)
    op.alter_column("task", "idp_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("task", "description", existing_type=sa.TEXT(), nullable=True)
    op.alter_column("task", "name", existing_type=sa.VARCHAR(length=100), nullable=True)
    op.drop_constraint(None, "idp", type_="foreignkey")
    op.create_foreign_key(
        "idp_director_id_fkey", "idp", "employee", ["director_id"], ["id"]
    )
    op.alter_column("idp", "employee_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("idp", "title", existing_type=sa.VARCHAR(length=100), nullable=True)
    op.alter_column(
        "control", "title", existing_type=sa.VARCHAR(length=100), nullable=True
    )
    op.alter_column("comment", "task_id", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "comment", "body_comment", existing_type=sa.VARCHAR(length=200), nullable=True
    )
    # ### end Alembic commands ###
