"""Task impovements

Revision ID: b2a9377b36eb
Revises: 634eec8ed76d
Create Date: 2024-01-25 20:37:36.354624

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2a9377b36eb"
down_revision: Union[str, None] = "634eec8ed76d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("description", sa.Text(), nullable=True))
    op.add_column("task", sa.Column("date_start", sa.Date(), nullable=True))
    op.add_column("task", sa.Column("date_end", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "date_end")
    op.drop_column("task", "date_start")
    op.drop_column("task", "description")
    # ### end Alembic commands ###
