"""Tasks enums

Revision ID: d835d4b41c39
Revises: edb9f5f397c2
Create Date: 2024-01-30 00:28:00.679531

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic_postgresql_enum import TableReference

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d835d4b41c39"
down_revision: Union[str, None] = "edb9f5f397c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "statusprogress",
        ["in_work", "done"],
        [TableReference("task", "status_progress")],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        "public",
        "statusaccept",
        ["accepted", "not_accepted", "canceled"],
        [TableReference("task", "status_accept")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        "public",
        "statusaccept",
        ["ACCEPTED", "NOT_ACCEPTED", "CANCELED"],
        [TableReference("task", "status_accept")],
        enum_values_to_rename=[],
    )
    op.sync_enum_values(
        "public",
        "statusprogress",
        ["IN_WORK", "DONE"],
        [TableReference("task", "status_progress")],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
