"""Fix task deleting

Revision ID: f7b8f15e5099
Revises: c31f7c66f358
Create Date: 2024-02-01 01:47:24.082051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7b8f15e5099'
down_revision: Union[str, None] = 'c31f7c66f358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_idp_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'idp', ['idp_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_idp_id_fkey', 'task', 'idp', ['idp_id'], ['id'])
    # ### end Alembic commands ###
