"""Added last_request column

Revision ID: 9d25b25e6777
Revises: 632fc967fc35
Create Date: 2024-02-10 22:36:44.619408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d25b25e6777'
down_revision: Union[str, None] = '632fc967fc35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee', sa.Column('last_request', sa.DateTime(), nullable=True))
    op.drop_constraint('employee_department_id_fkey', 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'department', ['department_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key('employee_department_id_fkey', 'employee', 'department', ['department_id'], ['id'], ondelete='CASCADE')
    op.drop_column('employee', 'last_request')
    # ### end Alembic commands ###
