"""Delete status models

Revision ID: 38634753e322
Revises: 03763e1af028
Create Date: 2024-01-25 02:19:19.433035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38634753e322'
down_revision: Union[str, None] = '03763e1af028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('IN_WORK', 'NOT_COMPLETED', 'DONE', 'CANCELED', name='statusidp').create(op.get_bind())
    sa.Enum('ACCEPTED', 'NOT_ACCEPTED', 'CANCELED', name='statusaccept').create(op.get_bind())
    sa.Enum('IN_WORK', 'DONE', name='statusprogress').create(op.get_bind())
    op.drop_constraint('idp_status_idp_id_fkey', 'idp', type_='foreignkey')
    op.drop_constraint('task_status_accept_id_fkey', 'task', type_='foreignkey')
    op.drop_constraint('task_status_progress_id_fkey', 'task', type_='foreignkey')
    op.drop_table('taskStatusProgress')
    op.drop_table('statusIdp')
    op.drop_table('request')
    op.drop_table('taskStatusAccept')
    op.add_column('idp', sa.Column('status_idp', postgresql.ENUM('IN_WORK', 'NOT_COMPLETED', 'DONE', 'CANCELED', name='statusidp', create_type=False), nullable=True))
    op.drop_column('idp', 'status_idp_id')
    op.add_column('task', sa.Column('status_progress', postgresql.ENUM('IN_WORK', 'DONE', name='statusprogress', create_type=False), nullable=True))
    op.add_column('task', sa.Column('status_accept', postgresql.ENUM('ACCEPTED', 'NOT_ACCEPTED', 'CANCELED', name='statusaccept', create_type=False), nullable=True))
    op.drop_column('task', 'status_progress_id')
    op.drop_column('task', 'status_accept_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status_accept_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('status_progress_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('task_status_progress_id_fkey', 'task', 'taskStatusProgress', ['status_progress_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('task_status_accept_id_fkey', 'task', 'taskStatusAccept', ['status_accept_id'], ['id'], ondelete='SET NULL')
    op.drop_column('task', 'status_accept')
    op.drop_column('task', 'status_progress')
    op.add_column('idp', sa.Column('status_idp_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('idp_status_idp_id_fkey', 'idp', 'statusIdp', ['status_idp_id'], ['id'], ondelete='SET NULL')
    op.drop_column('idp', 'status_idp')
    op.create_table('taskStatusAccept',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"taskStatusAccept_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='taskStatusAccept_pkey')
    )
    op.create_table('request',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('letter', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('director_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['employee.id'], name='request_director_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='request_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='request_pkey')
    )
    op.create_table('statusIdp',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"statusIdp_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='statusIdp_pkey')
    )
    op.create_table('taskStatusProgress',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"taskStatusProgress_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='taskStatusProgress_pkey')
    )
    sa.Enum('IN_WORK', 'DONE', name='statusprogress').drop(op.get_bind())
    sa.Enum('ACCEPTED', 'NOT_ACCEPTED', 'CANCELED', name='statusaccept').drop(op.get_bind())
    sa.Enum('IN_WORK', 'NOT_COMPLETED', 'DONE', 'CANCELED', name='statusidp').drop(op.get_bind())
    # ### end Alembic commands ###
