"""Refactor models

Revision ID: c3d2cfe0e2d1
Revises: 03763e1af028
Create Date: 2024-01-25 00:56:34.158142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d2cfe0e2d1'
down_revision: Union[str, None] = '03763e1af028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    op.alter_column('idp', 'status_idp_id',
               existing_type=sa.INTEGER(),
               type_=sa.Enum('IN_WORK', 'NOT_COMPLETED', 'DONE', 'CANCELED', name='statusidp'),
               existing_nullable=True)
    op.drop_constraint('idp_status_idp_id_fkey', 'idp', type_='foreignkey')
    op.add_column('task', sa.Column('status_progress', sa.Enum('IN_WORK', 'DONE', name='statusprogress'), nullable=True))
    op.add_column('task', sa.Column('status_accept', sa.Enum('ACCEPTED', 'NOT_ACCEPTED', 'CANCELED', name='statusaccept'), nullable=True))
    op.drop_constraint('task_status_progress_id_fkey', 'task', type_='foreignkey')
    op.drop_constraint('task_status_accept_id_fkey', 'task', type_='foreignkey')
    op.drop_column('task', 'status_progress_id')
    op.drop_column('task', 'status_accept_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('status_accept_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('status_progress_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('task_status_accept_id_fkey', 'task', 'taskStatusAccept', ['status_accept_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('task_status_progress_id_fkey', 'task', 'taskStatusProgress', ['status_progress_id'], ['id'], ondelete='SET NULL')
    op.drop_column('task', 'status_accept')
    op.drop_column('task', 'status_progress')
    op.create_foreign_key('idp_status_idp_id_fkey', 'idp', 'statusIdp', ['status_idp_id'], ['id'], ondelete='SET NULL')
    op.alter_column('idp', 'status_idp_id',
               existing_type=sa.Enum('IN_WORK', 'NOT_COMPLETED', 'DONE', 'CANCELED', name='statusidp'),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_table('request',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('letter', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('director_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['director_id'], ['employee.id'], name='request_director_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], name='request_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='request_pkey')
    )
    # ### end Alembic commands ###
