# Generated by Django 4.2.9 on 2024-02-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="last_request",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последний запрос"
            ),
        ),
    ]
