# Generated by Django 4.2.9 on 2024-01-25 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='department_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='director',
            new_name='director_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='grade',
            new_name='grade_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='post',
            new_name='post_id',
        ),
    ]
