# Generated by Django 4.2.9 on 2024-01-25 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_department_employee_department_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department_id',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='director_id',
            new_name='director',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='grade_id',
            new_name='grade',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='post_id',
            new_name='post',
        ),
    ]
